package me.proton.android.calendar.common.provider

import android.content.Context
import android.content.SharedPreferences
import androidx.security.crypto.EncryptedSharedPreferences
import androidx.security.crypto.MasterKey
import dagger.hilt.android.qualifiers.ApplicationContext
import me.proton.android.calendar.domain.ValueKey
import me.proton.android.calendar.domain.ValueStore
import me.proton.android.calendar.domain.ValueStoreProvider
import javax.inject.Inject

class ValueStoreProviderImpl @Inject constructor(
    private val sharedPreferencesProvider: SharedPreferencesProvider
) : ValueStoreProvider {

    private val valueStores = mutableMapOf<String, ValueStore>()

    inner class ValueStoreImpl(private val sharedPreferences: SharedPreferences) : ValueStore {

        @Synchronized
        override fun putString(key: String, value: String) = sharedPreferences.edit().putString(
            key,
            value
        ).apply()

        @Synchronized
        override fun getString(key: String): String? = sharedPreferences.getString(key, null)

        @Synchronized
        override fun putLong(key: String, value: Long) = sharedPreferences.edit().putLong(
            key,
            value
        ).apply()

        @Synchronized
        override fun getLong(key: String): Long? =
            if (sharedPreferences.contains(key)) sharedPreferences.getLong(key, 0L) else null

        @Synchronized
        override fun putBoolean(key: String, value: Boolean) = sharedPreferences.edit().putBoolean(
            key,
            value
        ).apply()

        @Synchronized
        override fun getBoolean(key: String): Boolean? =
            if (sharedPreferences.contains(key)) sharedPreferences.getBoolean(key, true) else null

        @Synchronized
        override fun putStringInSet(setName: String, key: String, value: String) = putString("$setName~$key", value)

        @Synchronized
        override fun getStringFromSet(setName: String, key: String): String? = getString("$setName~$key")

        @Synchronized
        override fun putLongInSet(setName: String, key: String, value: Long) = putLong("$setName~$key", value)

        @Synchronized
        override fun getLongFromSet(setName: String, key: String): Long? = getLong("$setName~$key")

        @Synchronized
        override fun clearAll() = sharedPreferences.edit().clear().apply()

        @Synchronized
        override fun removeKey(key: String) = sharedPreferences.edit().remove(key).apply()

        @Synchronized
        override fun removeKeySet(setName: String) {
            val editor = sharedPreferences.edit()
            sharedPreferences.all.filter { it.key.startsWith("$setName~") }.forEach { editor.remove(it.key) }
            editor.apply()
        }

        override fun removeKeyFromSet(setName: String, key: String) = sharedPreferences.edit().remove("$setName~$key").apply()
    }

    @Synchronized
    override fun provideValueStore(userId: String): ValueStore {
        return valueStores.getOrPut(userId) {
            ValueStoreImpl(sharedPreferencesProvider.provideSharedPreferencesFor(userId)).also {
                // TODO remove User Passphrase that used to be saved in the prefs
                it.removeKey(ValueKey.USER_PASSPHRASE)
            }
        }
    }

}

// TODO instrumented test
class SharedPreferencesProvider @Inject constructor(@ApplicationContext private val applicationContext: Context) {

    private val encryptedSharedPreferences = mutableMapOf<String, SharedPreferences>()

    // MasterKey for EncryptedSharedPreferences, generated by androidx library
    private val masterKey by lazy {
        MasterKey.Builder(applicationContext)
            .setKeyScheme(MasterKey.KeyScheme.AES256_GCM)
            .build()
    }

    // TODO if this goes wrong, all bets are off -- handle this on application init
    @Throws(Exception::class)
    fun provideSharedPreferencesFor(userId: String) : SharedPreferences {
        return encryptedSharedPreferences.getOrPut(userId) {
            EncryptedSharedPreferences.create(
                applicationContext,
                userId,
                masterKey,
                EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,
                EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM
            )
        }
    }
}
